import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import {
  BackgroundImage,
  Box,
  Button,
  Center,
  createStyles,
  Flex,
  Group,
  NumberInput,
  Paper,
  Text,
  Title,
} from "@mantine/core";
import { useState } from "react";
import { DateRangePickerValue, DateRangePicker } from "@mantine/dates";
import { BannerCard } from "@/components/Home/bannerCard";
import { Faqs } from "@/components/Home/Accordion";
// import { TopCities } from "@/components/Home/TopCities";
import TopCities from "@/components/Home/TopCities";

const inter = Inter({ subsets: ["latin"] });

const useStyles = createStyles((theme) => ({
  card: {
    width: "100%",
    height: 600,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "flex-end",
    backgroundSize: "cover",
    backgroundPosition: "center",
    // opacity: 0.7,
  },

  title: {
    fontFamily: "'VT323', monospace",
    fontWeight: 400,
    color: theme.white,
    lineHeight: 1.2,
    textAlign: "center",

    [theme.fn.largerThan("xs")]: {
      fontSize: 80,
    },
    [theme.fn.smallerThan("xs")]: {
      fontSize: 50,
    },
    marginTop: theme.spacing.xs,
  },

  title1: {
    fontFamily: "Roboto Mono, monospace",
    fontWeight: 400,
    color: theme.white,
    textAlign: "center",
    // lineHeight: 1.2,

    [theme.fn.largerThan("xs")]: {
      fontSize: 40,
    },
    [theme.fn.smallerThan("xs")]: {
      fontSize: 30,
    },
    marginTop: theme.spacing.xs,
  },

  category: {
    color: "indianred",
    opacity: 0.7,
    fontWeight: 700,
    textTransform: "uppercase",
  },
  box: {
    [theme.fn.largerThan("xs")]: {
      marginTop: theme.spacing.xl * 3,
    },
    [theme.fn.smallerThan("xs")]: {
      marginTop: theme.spacing.xs,
    },
  },
  flex: {
    [theme.fn.largerThan("sm")]: {
      flexDirection: "row",
    },
    [theme.fn.smallerThan("sm")]: {
      flexDirection: "column",
    },
  },
}));

function Card() {
  const { classes } = useStyles();
  const [value, setValue] = useState<DateRangePickerValue>([null, null]);
  console.log(value);

  return (
    <BackgroundImage className={classes.card} src="/hotel2.avif">
      <Center
        sx={{
          display: "flex",
          justifyContent: "space-between",
          flexDirection: "column",
          height: "100%",
          color: "black",
        }}
      >
        <Box className={classes.box}>
          <div>
            {/* <Text className={classes.category} size="xs">
              category
            </Text> */}
            <Text className={classes.title}>Book Your Stay</Text>
            <Title order={1} className={classes.title1}>
              With Hotel-web
            </Title>
          </div>

          <Flex gap="md" sx={{ marginTop: "9rem" }} className={classes.flex}>
            <DateRangePicker
              size="lg"
              placeholder="Pick dates range"
              value={value}
              onChange={setValue}
            />
            <NumberInput size="lg" placeholder="Select no.of Rooms" />
            <NumberInput size="lg" placeholder="Select no.of People" />
            <Button size="lg">Search</Button>
          </Flex>
        </Box>
      </Center>
    </BackgroundImage>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link
          href="https://fonts.googleapis.com/css2?family=VT323&display=swap"
          rel="stylesheet"
        ></link> */}
      </Head>
      <Card />
      <BannerCard />

      <Title my="2rem" order={3}>
        Top Cities
      </Title>
      <TopCities />

      <Faqs />
    </>
  );
}
